[package]
name = "skedgy"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
futures = "0.3.30"
humantime = "2.1.0"
log = "0.4.22"
tokio = { version = "1.40.0", features = ["time", "rt"] }
